Implement step 3
Relatively painless apart from the rather obtuse error:

  error: expecting a top level declaration

Which was the result of having calls to `repl_env.set(...)` in the
file. Moving it to `apply` fixed it, not sure why having statements at
file level isn't kosher, maybe a JVM hangover?